---
apiVersion: v1
data:
    password: cGFzc3dvcmQ=
    username: YWRtaW4=
kind: Secret
metadata:
    name: spoke-worker-0-1-bmc-secret
    namespace: spoke-0
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
    name: spoke-worker-0-1-bmh
    namespace: spoke-0
    annotations:
      inspect.metal3.io: enabled
      bmac.agent-install.openshift.io/hostname: "spoke-worker-0-1"
      bmac.agent-install.openshift.io/role: "worker"
    labels:
      infraenvs.agent-install.openshift.io: "spoke-0"
spec:
    bmc:
      address: redfish+https://192.168.124.1:8000/redfish/v1/Systems/1d768800-3f74-43b6-97e0-479b2db5a07c
      credentialsName: spoke-worker-0-1-bmc-secret
      disableCertificateVerification: true
    bootMACAddress: 52:54:00:fc:2b:30
    automatedCleaningMode: disabled
    online: true
