---
apiVersion: v1
data:
    password: cGFzc3dvcmQ=
    username: YWRtaW4=
kind: Secret
metadata:
    name: spoke-master-0-1-bmc-secret
    namespace: spoke-0
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
    name: spoke-master-0-1-bmh
    namespace: spoke-0
    annotations:
      inspect.metal3.io: enabled
      bmac.agent-install.openshift.io/hostname: "spoke-master-0-1"
      bmac.agent-install.openshift.io/role: "master"
    labels:
      infraenvs.agent-install.openshift.io: "spoke-0"
spec:
    bmc:
      address: redfish+https://192.168.124.1:8000/redfish/v1/Systems/5584f1ee-c526-480a-87f2-90b147e87f7e
      credentialsName: spoke-master-0-1-bmc-secret
      disableCertificateVerification: true
    bootMACAddress: 52:54:00:45:b0:d6
    automatedCleaningMode: disabled
    online: true
