---
apiVersion: v1
data:
    password: cGFzc3dvcmQ=
    username: YWRtaW4=
kind: Secret
metadata:
    name: spoke-master-0-0-bmc-secret
    namespace: spoke-0
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
    name: spoke-master-0-0-bmh
    namespace: spoke-0
    annotations:
      inspect.metal3.io: enabled
      bmac.agent-install.openshift.io/hostname: "spoke-master-0-0"
      bmac.agent-install.openshift.io/role: "master"
    labels:
      infraenvs.agent-install.openshift.io: "spoke-0"
spec:
    bmc:
      address: redfish+https://192.168.124.1:8000/redfish/v1/Systems/13761181-3b5c-4458-b11b-cae9e3184b95
      credentialsName: spoke-master-0-0-bmc-secret
      disableCertificateVerification: true
    bootMACAddress: 52:54:00:f9:55:10
    automatedCleaningMode: disabled
    online: true
